---
- hosts: all
  gather_facts: false
  pre_tasks:
    - name: Check python is installed
      raw:  test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false
    - name: Gathering Facts
      setup:
  tasks:
    - name: check password settings
      delegate_to: localhost
      run_once: true
      fail:
        msg: "Change the password: you are using <<changeit>> as value for one or more variables (mesos_password, marathon_password, chronos_password) "
      when: item == "changeit"
      with_items:
        - "{{mesos_password}}"
        - "{{marathon_password}}"
        - "{{chronos_password}}"
    - name: set hostname to local ipv4 address
      lineinfile:
        dest: /etc/hosts
        line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}"

- hosts: mesos_masters
  vars:
    docker_bridge_ip_cidr: "172.0.17.1/24"
  roles:
     - { role: indigo-dc.consul, consul_mode: "server"  }
     - { role: indigo-dc.zookeeper }
     - { role: indigo-dc.mesos, mesos_install_mode: "master"}
     - { role: indigo-dc.marathon }
     - { role: indigo-dc.chronos }

- hosts: mesos_slaves
  vars:
    docker_bridge_ip_cidr: "172.0.17.1/24"
  roles:
    - { role: indigo-dc.consul, consul_mode: "agent"  }
    - { role: indigo-dc.mesos, mesos_install_mode: "slave" }

- hosts: load_balancers
  vars:
    docker_bridge_ip_cidr: "172.0.17.1/24"
  roles:
    - { role: indigo-dc.consul, consul_mode: "agent" }
    - { role: indigo-dc.marathon-lb, marathon_lb_auth_creds: "{{marathon_username}}:{{marathon_password}}" }
    - { role: indigo-dc.keepalived }
