---
load_balancers_group: "load_balancers"
load_balancers: "
        {%- if load_balancers_list is defined -%}
             {{load_balancers_list}}
        {%- else -%}
              {{groups[load_balancers_group]}}
        {%- endif -%}
"
first_load_balancer_ip: "
        {%- if load_balancers_list is defined -%}
             {{load_balancers_list[0]}}
        {%- else -%}
              {{hostvars[groups[load_balancers_group][0]]['ansible_eth0']['ipv4']['address']}}
        {%- endif -%}
"
keepalived_role: "{% if ansible_default_ipv4.address == first_load_balancer_ip %}master{% else %}slave{% endif %}"
keepalived_version: 'latest'
keepalived_image: "indigodatacloud/keepalived:{{keepalived_version}}"
keepalived_priority: "{%- if keepalived_role == 'master' -%}150{%- else -%}100{%- endif -%}"

