heat_template_version: 2014-10-16

description: >
  This is a nested stack that defines a single Mesos slave, This stack is
  included by an ResourceGroup resource in the parent template
  (mesoscluster.yaml).

parameters:

  server_image:
    type: string
    description: glance image used to boot the server

  server_name:
    type: string

  server_flavor:
    type: string
    description: flavor to use when booting the server

  ssh_key_name:
    type: string
    description: name of ssh key to be provisioned on our server

  network:
    type: string
    description: Network from which to allocate fixed addresses.

  security_groups:
    type: comma_delimited_list

  virtual_ip:
    type: string
    description: VIP address


resources:


  ######################################################################
  #
  # software configs.  these are components that are combined into
  # a multipart MIME user-data archive.
  #

  loadbalancer:
    type: OS::Nova::Server
    properties:
      name: {get_param: server_name}
      image: {get_param: server_image}
      flavor: {get_param: server_flavor}
      key_name: {get_param: ssh_key_name}
      user_data_format: SOFTWARE_CONFIG
      networks:
        - port: {get_resource: lb_port }

  lb_port:
    type: OS::Neutron::Port
    properties:
      network: {get_param: network}
      allowed_address_pairs:
       - ip_address: {get_param: virtual_ip } 
      security_groups: {get_param: security_groups}
      replacement_policy: AUTO


outputs:

  loadbalancer_ip:
    value: {get_attr: [lb_port, fixed_ips, 0, ip_address]}
    description: >
      This is the address of the LoadBalancer  node.

  loadbalancer_id:
    value: {get_resource: loadbalancer}

